version: '3.2'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./config/containers/development/rails/Dockerfile
    working_dir: /var/www/herepup
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_MAX_THREADS: 8
      WEB_CONCURRENCY: 4
      PORT: 3003
    command: sh ./config/containers/bash/rails_start.sh
    volumes:
      - .:/var/www/herepup
    ports:
      - "3003:3003"
    expose:
      - "3003"
    links:
      - db
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - backend
    ports:
      - "8088:8080"
    environment:
      - API_URL=http://0.0.0.0:3003/swagger_doc
